### ISSUE TITLE
Plug > Plugin

### ISSUE THREAD

**Issue by yefim** [anglinb/dotfiles#1]
You gotta get on that new shit: https://github.com/junegunn/vim-plug

[Check it 💯 ](https://github.com/yefim/dotfiles/blob/master/.vimrc)

**Comment by anglinb** [comment]
Lol @yefim isn't almost the same as Vundle?

**Comment by yefim** [comment]
Yes it is, but it's actively maintained.

**Comment by anglinb** [comment]
Haha I was totally gonna get to that. 😛 how are you dude?

**Comment by yefim** [comment]
I'm good 👌 I was doing some winter/new year's cleaning 😂 have you finished school yet?

**Comment by anglinb** [comment]
Nice nice--no I finish up in May. Going to be going full time at GitHub next fall. You still in the bay?

**Comment by yefim** [comment]
Yep, still in SF 🙆‍♂️ GitHub is a dope co 👍
